export const CATEGORY_ACTION_TYPE = {
    SET_CATEGORY: 'category/SET_CATEGORY',
    FETCH_CATEGORY_START: 'category/FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCESS: 'category/FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'category/FETCH_CATEGORY_FAILURE'
}